"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requirePagePermission } from "@/lib/authorization";
import { requireCompanyId } from "@/lib/company-scope";
import { supabaseAdmin } from "@/lib/supabase-admin";

const path="/delivery-network/associates?view=referrals";
const clean=(form:FormData,key:string)=>String(form.get(key)??"").trim();
const finish=(kind:"notice"|"error",message:string):never=>redirect(`${path}&${kind}=${encodeURIComponent(message)}`);

export async function saveReferralProgram(form:FormData){const auth=await requirePagePermission("delivery_associates","edit");const company=requireCompanyId(auth);try{if(auth.readOnly||!supabaseAdmin)throw new Error("Editing is unavailable.");const id=clean(form,"id"),name=clean(form,"name"),stationId=clean(form,"station_id"),source=clean(form,"qualification_source"),terms=clean(form,"terms"),from=clean(form,"effective_from"),to=clean(form,"effective_to");const amount=Number(clean(form,"reward_amount")),days=Number(clean(form,"qualifying_days"));if(name.length<2||name.length>120)throw new Error("Enter a program name.");if(!Number.isFinite(amount)||amount<=0)throw new Error("Reward amount must be greater than zero.");if(!Number.isInteger(days)||days<1||days>365)throw new Error("Qualifying days must be between 1 and 365.");if(!["calendar_days","biometric_present_days","amazon_delivery_days"].includes(source))throw new Error("Choose a valid qualification source.");if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||to&&!/^\d{4}-\d{2}-\d{2}$/.test(to)||to&&to<from)throw new Error("Choose valid effective dates.");if(terms.length<5||terms.length>2000)throw new Error("Enter clear referral terms.");if(stationId){let station=supabaseAdmin.from("stations").select("id").eq("company_id",company).eq("id",stationId).eq("is_active",true);if(!auth.hasAllLocationAccess)station=station.in("id",auth.locationScopeIds.length?auth.locationScopeIds:["00000000-0000-0000-0000-000000000000"]);const result=await station.maybeSingle();if(result.error||!result.data)throw new Error("Station is outside your access scope.");}const payload={company_id:company,station_id:stationId||null,name,reward_amount:amount,qualification_source:source,qualifying_days:days,effective_from:from,effective_to:to||null,terms,is_active:form.has("is_active"),updated_at:new Date().toISOString()};const result=id?await supabaseAdmin.from("workforce_referral_programs").update(payload).eq("company_id",company).eq("id",id):await supabaseAdmin.from("workforce_referral_programs").insert({...payload,created_by:auth.userId});if(result.error)throw new Error(result.error.message);revalidatePath("/delivery-network/associates");}catch(error){finish("error",error instanceof Error?error.message:"Unable to save referral program.");}finish("notice","Referral program saved.");}

export async function reviewReferral(form:FormData){const auth=await requirePagePermission("delivery_associates","edit");const company=requireCompanyId(auth);try{if(auth.readOnly||!supabaseAdmin)throw new Error("Editing is unavailable.");const id=clean(form,"id"),decision=clean(form,"decision"),remarks=clean(form,"remarks");const current=await supabaseAdmin.from("workforce_referrals").select("*,program:workforce_referral_programs(id)").eq("company_id",company).eq("id",id).maybeSingle();if(current.error||!current.data)throw new Error("Referral was not found.");if(!auth.hasAllLocationAccess&&current.data.preferred_station_id&&!auth.locationScopeIds.includes(current.data.preferred_station_id))throw new Error("Referral is outside your station scope.");if(decision==="reject"){if(remarks.length<3)throw new Error("Enter a rejection reason.");const result=await supabaseAdmin.from("workforce_referrals").update({status:"rejected",decision_remarks:remarks,approved_by:auth.userId,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("company_id",company).eq("id",id).in("status",["submitted","linked","qualified"]);if(result.error)throw new Error(result.error.message);revalidatePath("/delivery-network/associates");finish("notice","Referral rejected.");}
let referredId=current.data.referred_workforce_id as string|null;if(!referredId){const person=await supabaseAdmin.from("workforce").select("id,date_of_join").eq("company_id",company).or(`mobile.eq.${current.data.referred_mobile},mobile.eq.${current.data.referred_country_code}${current.data.referred_mobile}`).is("deleted_at",null).limit(1);if(person.error)throw new Error(person.error.message);referredId=person.data?.[0]?.id??null;}let progress=0;if(referredId){if(current.data.qualification_source_snapshot==="calendar_days"){const person=await supabaseAdmin.from("workforce").select("date_of_join").eq("company_id",company).eq("id",referredId).maybeSingle();if(person.error)throw new Error(person.error.message);if(person.data?.date_of_join)progress=Math.max(0,Math.floor((Date.now()-new Date(`${person.data.date_of_join}T00:00:00+05:30`).getTime())/86400000)+1);}else if(current.data.qualification_source_snapshot==="biometric_present_days"){const attendance=await supabaseAdmin.from("attendance_daily").select("punch_date").eq("company_id",company).eq("workforce_id",referredId).eq("status","P");if(attendance.error)throw new Error(attendance.error.message);progress=new Set((attendance.data??[]).map(row=>row.punch_date)).size;}else{const lines=await supabaseAdmin.from("workforce_payroll_lines").select("work_date").eq("company_id",company).eq("workforce_id",referredId).gt("shipment_count",0);if(lines.error)throw new Error(lines.error.message);progress=new Set((lines.data??[]).map(row=>row.work_date)).size;}}
const qualified=Boolean(referredId)&&progress>=Number(current.data.qualifying_days_snapshot);if(decision==="approve"){if(!qualified)throw new Error(`Referral has ${progress} of ${current.data.qualifying_days_snapshot} qualifying days.`);const reference=`REFERRAL:${id}`;const existing=await supabaseAdmin.from("workforce_adjustments").select("id").eq("company_id",company).eq("external_reference",reference).maybeSingle();if(existing.error)throw new Error(existing.error.message);if(!existing.data){const adjustment=await supabaseAdmin.from("workforce_adjustments").insert({company_id:company,workforce_id:current.data.referrer_workforce_id,adjustment_type:"earning",category:"referral_bonus",amount:current.data.reward_amount_snapshot,effective_date:new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),reason:`Referral reward for ${current.data.referred_full_name}`,external_reference:reference,status:"pending",requested_by:auth.userId});if(adjustment.error)throw new Error(adjustment.error.message);}const result=await supabaseAdmin.from("workforce_referrals").update({referred_workforce_id:referredId,qualification_progress:progress,status:"approved",qualified_at:current.data.qualified_at||new Date().toISOString(),approved_at:new Date().toISOString(),approved_by:auth.userId,decision_remarks:remarks||null,updated_at:new Date().toISOString()}).eq("company_id",company).eq("id",id);if(result.error)throw new Error(result.error.message);revalidatePath("/delivery-network/adjustments");revalidatePath("/delivery-network/associates");finish("notice","Referral reward sent for maker-checker approval.");}
const result=await supabaseAdmin.from("workforce_referrals").update({referred_workforce_id:referredId,qualification_progress:progress,status:qualified?"qualified":referredId?"linked":"submitted",qualified_at:qualified?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("company_id",company).eq("id",id);if(result.error)throw new Error(result.error.message);revalidatePath("/delivery-network/associates");}catch(error){finish("error",error instanceof Error?error.message:"Unable to review referral.");}finish("notice","Referral status refreshed.");}
