import { AppShell } from "@/components/app-shell";
import { PageHead } from "@/components/page-head";
import { SubmitButton } from "@/components/submit-button";
import { requirePagePermission } from "@/lib/authorization";
import { requireCompanyId } from "@/lib/company-scope";
import { inferFormTypeFromLocation, loadCodLocations, locationModelName } from "@/lib/ops-pulse/cod";
import { loadNetworkPlanning, startOfPlanningWeek } from "@/lib/ops-pulse/network-planning";
import { loadServiceNetworkRules } from "@/lib/ops-pulse/service-network";
import { archiveNetworkSector, removeServiceNetworkMaster, saveNetworkSector, saveServiceNetworkMaster } from "./actions";

export const dynamic = "force-dynamic";
export default async function ServiceNetworkMasterPage({ searchParams }: { searchParams?: { station?: string; sector?: string; notice?: string; error?: string } }) {
  const authorization = await requirePagePermission("service_network_master", "access");
  const companyId = requireCompanyId(authorization);
  const [locationsResult, rulesResult] = await Promise.all([loadCodLocations(companyId, authorization.locationScopeIds, authorization.hasAllLocationAccess), loadServiceNetworkRules(companyId)]);
  const locations = locationsResult.locations.filter(location => ["amazon", "flipkart"].includes(inferFormTypeFromLocation(location)));
  const stationCode = String(searchParams?.station ?? locations[0]?.station_code ?? "").toUpperCase();
  const location = locations.find(row => row.station_code === stationCode) ?? locations[0];
  const rule = rulesResult.rows.find(row => row.stationCode === location?.station_code);
  const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata" }).format(new Date());
  const planning = location ? await loadNetworkPlanning({ companyId, stationId: location.id, weekStart: startOfPlanningWeek(today), selectedDate: today, rule }) : null;
  const selectedSector = planning?.sectors.find(sector => sector.id === searchParams?.sector) ?? null;
  const permission = authorization.permissions.service_network_master;
  return <AppShell active="Network Planning Master" pageCode="service_network_master"><div className="ops-command-center capacity-workspace">
    <PageHead eyebrow="Ops Masters" title="Network Planning Master" subtitle="Maintain the confirmed station boundary, sector ownership, pincodes and bike/van productivity used by OpsPulse planning." action={<a className="button secondary compact" href="/ops-pulse/service-network">Open Network Planning</a>}/>
    {searchParams?.error || locationsResult.error || rulesResult.error ? <div className="message-panel error">{searchParams?.error || locationsResult.error || rulesResult.error}</div> : null}{searchParams?.notice ? <div className="message-panel success">{searchParams.notice}</div> : null}
    <section className="panel"><div className="panel-head"><div><h2>Confirmed station rule</h2><p className="subtle">Only active stations already present in OpsPulse are available. External maps are reference layers and never activate a station automatically.</p></div><form method="get"><label>Station<select name="station" defaultValue={location?.station_code}>{locations.map(row => <option key={row.id} value={row.station_code}>{row.station_code} · {row.station_name || row.city} · {locationModelName(row)}</option>)}</select></label><button className="button secondary compact">View</button></form></div>
      {location ? <form action={saveServiceNetworkMaster} className="panel-body"><input type="hidden" name="station_code" value={location.station_code}/><div className="form-grid"><label>Jurisdiction owner<input className="field" name="jurisdiction_owner" defaultValue={rule?.jurisdictionOwner || location.cluster_manager || location.aom || ""} placeholder="Manager or team"/></label><label>Service radius (km)<input className="field" type="number" step="0.1" min="0.1" name="service_radius_km" defaultValue={rule?.serviceRadiusKm ?? ""} required/></label><label>Bike planning SPR<input className="field" type="number" step="0.1" min="0.1" name="bike_spr" defaultValue={rule?.bikeSpr ?? ""} required/></label><label>Van planning SPR<input className="field" type="number" step="0.1" min="0.1" name="van_spr" defaultValue={rule?.vanSpr ?? ""} required/></label><label>Capacity buffer %<input className="field" type="number" step="0.1" min="0" name="buffer_percent" defaultValue={rule?.bufferPercent ?? 10}/></label><label>Effective from<input className="field" type="date" name="effective_from" defaultValue={rule?.effectiveFrom ?? new Date().toISOString().slice(0,10)} required/></label><label>Effective to<input className="field" type="date" name="effective_to" defaultValue={rule?.effectiveTo ?? ""}/></label><label className="full-span">Approved service pincodes<textarea className="field" name="pincodes" defaultValue={(rule?.pincodeOwnership ?? []).join(", ")} placeholder="524101, 524121, 524123" rows={3}/><small className="field-hint">Add only serviceable pincodes confirmed by operations. Map labels remain suggestions until approved here.</small></label><label className="full-span">Pincode map coordinates <span className="subtle">(optional fallback)</span><textarea className="field" name="pincode_coordinates" defaultValue={Object.entries(rule?.pincodeCoordinates ?? {}).map(([code, point]) => `${code}, ${point.lat}, ${point.lng}`).join("\n")} placeholder={"524101, 14.1463, 79.8504\n524121, 13.6368, 80.0280"} rows={4}/><small className="field-hint">Coordinates are optional. The approved map layer is used first; these values fill only missing plotted pincodes.</small></label></div><label className="toggle-field"><input type="checkbox" name="is_active" defaultChecked={rule?.isActive ?? true}/><span>Active for planning</span></label>{permission.canEdit ? <div className="form-actions"><SubmitButton>Save station rule</SubmitButton>{rule?.id ? <button className="button danger" formAction={removeServiceNetworkMaster} name="id" value={rule.id}>Delete rule</button> : null}</div> : null}</form> : <div className="empty-cell">No eligible stations are available.</div>}
    </section>
    {location && planning?.schemaReady ? <section className="panel"><div className="panel-head"><div><h2>Station sectors</h2><p className="subtle">Split the confirmed service area into operational sectors and assign TL/SSA ownership.</p></div>{selectedSector ? <a className="button secondary compact" href={`?station=${location.station_code}`}>Add sector</a> : null}</div>
      <div className="panel-body"><div className="compact-summary-grid">{planning.sectors.map(sector => <a key={sector.id} href={`?station=${location.station_code}&sector=${sector.id}`} style={{ borderLeft: `4px solid ${sector.color}` }}><span className="subtle">{sector.code} · {sector.pincodes.length} pincodes</span><strong>{sector.name}</strong><small className="subtle">{sector.expectedDailyVolume.toLocaleString("en-IN")} volume · TL {sector.tlName || "unassigned"} · SSA {sector.ssaName || "unassigned"}</small></a>)}{!planning.sectors.length ? <div className="empty-cell">No sectors configured. Create the first sector below.</div> : null}</div></div>
      {permission.canEdit ? <form action={saveNetworkSector} className="panel-body" style={{ borderTop: "1px solid var(--border)" }}><input type="hidden" name="station_id" value={location.id}/><input type="hidden" name="station_code" value={location.station_code}/><input type="hidden" name="sector_id" value={selectedSector?.id ?? ""}/><div className="form-grid"><label>Sector code<input className="field" name="sector_code" defaultValue={selectedSector?.code ?? ""} placeholder="NORTH" required/></label><label>Sector name<input className="field" name="sector_name" defaultValue={selectedSector?.name ?? ""} placeholder="North Sector" required/></label><label>Colour<input className="field" type="color" name="color" defaultValue={selectedSector?.color ?? "#2563eb"}/></label><label>Expected daily volume<input className="field" type="number" min="0" name="expected_daily_volume" defaultValue={selectedSector?.expectedDailyVolume ?? 0} required/></label><label>Bike volume mix %<input className="field" type="number" min="0" max="100" step="0.1" name="bike_volume_percent" defaultValue={selectedSector?.bikeVolumePercent ?? 70}/><small className="field-hint">Remaining volume is planned as van capacity.</small></label><label>Team Leader<select className="field" name="tl_user_id" defaultValue={selectedSector?.tlUserId ?? ""}><option value="">Unassigned</option>{planning.planners.filter(user => ["TEAM_LEADER", "STATION_MANAGER", "ADMIN", "OWNER"].includes(user.roleCode)).map(user => <option key={user.id} value={user.id}>{user.name} · {user.roleName}</option>)}</select></label><label>Station Support Associate<select className="field" name="ssa_user_id" defaultValue={selectedSector?.ssaUserId ?? ""}><option value="">Unassigned</option>{planning.planners.filter(user => user.roleCode === "SSA").map(user => <option key={user.id} value={user.id}>{user.name}</option>)}</select></label><label className="full-span">Sector pincodes<textarea className="field" name="pincodes" rows={3} defaultValue={selectedSector?.pincodes.map(item => item.pincode).join(", ") ?? ""} placeholder="999001, 999002, 999003, 999004"/></label><label className="full-span">Notes<input className="field" name="notes" defaultValue={selectedSector?.notes ?? ""} placeholder="Mixed vehicle sector, temporary support rule…"/></label></div><label className="toggle-field"><input type="checkbox" name="manual_override"/><span>Allow pincode outside the current approved station boundary</span></label><label className="toggle-field"><input type="checkbox" name="shared_pincode_override"/><span>Allow split/shared pincode with another sector</span></label><div className="form-actions"><SubmitButton>{selectedSector ? "Update sector" : "Create sector"}</SubmitButton>{selectedSector ? <button className="button danger" formAction={archiveNetworkSector}>Archive sector</button> : null}</div></form> : null}
    </section> : planning && !planning.schemaReady ? <div className="message-panel error">{planning.error}</div> : null}
    <section className="panel"><div className="panel-head"><div><h2>Planning logic</h2><p className="subtle">Transparent and independently editable for every station.</p></div></div><div className="panel-body compact-summary-grid"><div><span className="subtle">Bike requirement</span><strong>Small ÷ Bike SPR + buffer</strong></div><div><span className="subtle">Van requirement</span><strong>Volumetric ÷ Van SPR + buffer</strong></div><div><span className="subtle">Actual IDs</span><strong>Shipment-active IDs</strong></div><div><span className="subtle">Actual vehicle mix</span><strong>DA designation mapping required</strong></div></div></section>
  </div></AppShell>;
}
