import { readAllRows } from "@/lib/supabase-pagination";
import { ArrowLeft, CheckCircle2, Download, LockKeyhole, RefreshCw, Send, WalletCards } from "lucide-react";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { PendingLink } from "@/components/pending-link";
import { SubmitButton } from "@/components/submit-button";
import { isCompanyOwner, requirePagePermission } from "@/lib/authorization";
import { requireCompanyId } from "@/lib/company-scope";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { changePayrollRunStatus, recalculatePayrollRun, setPayrollItemDisposition } from "../actions";

export const dynamic = "force-dynamic";
type Run = { id: string; run_number: string; period_start: string; period_end: string; status: string; worker_count: number; shipment_count: number; base_amount: number; incentive_amount: number; adjustment_amount: number; deduction_amount: number; net_amount: number; ready_count: number; hold_count: number; exception_count: number; source_updated_at: string | null; calculated_at: string | null; submitted_by: string | null; submitted_at: string | null; approved_at: string | null; paid_at: string | null; approval_remarks: string | null };
type Item = { id: string; workforce_id: string; dropx_id: string; worker_name: string; station_code: string | null; bank_account_no: string | null; ifsc_code: string | null; shipment_count: number; work_days: number; base_amount: number; incentive_amount: number; adjustment_amount: number; deduction_amount: number; gross_amount: number; net_amount: number; status: string; hold_reasons: unknown; provider_member_ids: unknown };
type Line = { id: string; source_type: string; work_date: string; provider_name: string | null; provider_member_id: string | null; shipment_count: number; activity_count: number; base_amount: number; incentive_amount: number; adjustment_amount: number; net_amount: number; calculation_source: string; calculation_snapshot: Record<string, unknown> };
type Event = { id: string; event_code: string; from_status: string | null; to_status: string | null; remarks: string | null; created_at: string };
function money(value: unknown) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(Number(value ?? 0)); }
function number(value: unknown) { return new Intl.NumberFormat("en-IN", { maximumFractionDigits: 0 }).format(Number(value ?? 0)); }
function words(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function strings(value: unknown) { return Array.isArray(value) ? value.map(String) : []; }
function maskedAccount(value: string | null) { const account = String(value ?? ""); return account ? `••••${account.slice(-4)}` : "Bank pending"; }

export default async function PayrollRunPage({ params, searchParams }: { params: { id: string }; searchParams?: { item?: string; notice?: string; error?: string } }) {
  const authorization = await requirePagePermission("workforce_payroll", "access");
  const companyId = requireCompanyId(authorization);
  if (!authorization.hasAllLocationAccess || !supabaseAdmin) return <AppShell active="Payroll Runs" pageCode="workforce_payroll"><section className="panel message-panel error"><div className="panel-body">Payroll detail requires database connectivity and all-location access.</div></section></AppShell>;
  const [runResult, itemResult, eventResult] = await Promise.all([
    supabaseAdmin.from("workforce_payroll_runs").select("id, run_number, period_start, period_end, status, worker_count, shipment_count, base_amount, incentive_amount, adjustment_amount, deduction_amount, net_amount, ready_count, hold_count, exception_count, source_updated_at, calculated_at, submitted_by, submitted_at, approved_at, paid_at, approval_remarks").eq("company_id", companyId).eq("id", params.id).maybeSingle(),
    readAllRows(supabaseAdmin.from("workforce_payroll_items").select("id, workforce_id, dropx_id, worker_name, station_code, bank_account_no, ifsc_code, shipment_count, work_days, base_amount, incentive_amount, adjustment_amount, deduction_amount, gross_amount, net_amount, status, hold_reasons, provider_member_ids").eq("company_id", companyId).eq("payroll_run_id", params.id).order("status").order("worker_name").order("id")),
    supabaseAdmin.from("workforce_payroll_events").select("id, event_code, from_status, to_status, remarks, created_at").eq("company_id", companyId).eq("payroll_run_id", params.id).order("created_at", { ascending: false })
  ]);
  if (runResult.error || !runResult.data) notFound();
  if (itemResult.error || eventResult.error) throw new Error(itemResult.error?.message ?? eventResult.error?.message ?? "Payroll detail is unavailable.");
  const run = runResult.data as Run;
  const items = (itemResult.data ?? []) as Item[];
  const events = (eventResult.data ?? []) as Event[];
  const selectedItem = items.find((item) => item.id === searchParams?.item) ?? null;
  const lineResult = selectedItem ? await supabaseAdmin.from("workforce_payroll_lines").select("id, source_type, work_date, provider_name, provider_member_id, shipment_count, activity_count, base_amount, incentive_amount, adjustment_amount, net_amount, calculation_source, calculation_snapshot").eq("company_id", companyId).eq("payroll_run_id", run.id).eq("payroll_item_id", selectedItem.id).order("work_date") : { data: [], error: null };
  if (lineResult.error) throw new Error(lineResult.error.message);
  const lines = (lineResult.data ?? []) as Line[];
  const canEdit = authorization.permissions.workforce_payroll.canEdit && !authorization.readOnly;
  const owner = isCompanyOwner(authorization) && !authorization.readOnly;
  const canApprove = owner && run.submitted_by !== authorization.userId;

  return <AppShell active="Payroll Runs" pageCode="workforce_payroll">
    <PendingLink className="wf-back-link" href="/delivery-network/payroll"><ArrowLeft size={15} /> Payroll register</PendingLink>
    <section className="wf-finance-hero compact"><div><span>Payroll snapshot · {run.status}</span><h1>{run.run_number}</h1><p>{run.period_start} to {run.period_end} · {number(run.worker_count)} included associates · source {run.source_updated_at ? new Date(run.source_updated_at).toLocaleString("en-IN") : "not timestamped"}</p></div><div className="wf-finance-actions"><PendingLink className="wf-command-secondary" href={`/api/workforce/payroll/${run.id}/export`}><Download size={15} /> Export CSV</PendingLink>{run.status === "draft" && canEdit ? <form action={recalculatePayrollRun}><input name="id" type="hidden" value={run.id} /><SubmitButton pendingText="Recalculating"><RefreshCw size={14} /> Recalculate</SubmitButton></form> : null}</div></section>
    {searchParams?.notice || searchParams?.error ? <section className={`panel message-panel ${searchParams.error ? "error" : "success"}`}><div className="panel-body"><strong>{searchParams.error ? "Action required" : "Completed"}</strong><p>{searchParams.error ?? searchParams.notice}</p></div></section> : null}
    <section className="wf-finance-kpis"><article><span><WalletCards size={18} /></span><small>Payable</small><strong>{money(run.net_amount)}</strong><em>Ready associates only</em></article><article><span><CheckCircle2 size={18} /></span><small>Ready</small><strong>{run.ready_count}</strong><em>{run.worker_count} included</em></article><article className={run.hold_count ? "attention" : "healthy"}><span><LockKeyhole size={18} /></span><small>Holds</small><strong>{run.hold_count}</strong><em>Resolve or exclude</em></article><article className={run.exception_count ? "attention" : "healthy"}><span><LockKeyhole size={18} /></span><small>Source exceptions</small><strong>{run.exception_count}</strong><em>Recalculate after fixing</em></article><article><span><Send size={18} /></span><small>Status</small><strong>{words(run.status)}</strong><em>{run.calculated_at ? `Calculated ${new Date(run.calculated_at).toLocaleString("en-IN")}` : "Pending"}</em></article></section>
    <section className="wf-payroll-breakdown"><div><small>Base</small><strong>{money(run.base_amount)}</strong></div><div><small>Incentives</small><strong>{money(run.incentive_amount)}</strong></div><div><small>Additions</small><strong>{money(run.adjustment_amount)}</strong></div><div><small>Deductions</small><strong>-{money(run.deduction_amount)}</strong></div><div><small>Shipments</small><strong>{number(run.shipment_count)}</strong></div></section>
    <section className="wf-payroll-workflow"><div className={run.status === "draft" ? "current" : "done"}><i>1</i><span><strong>Draft calculation</strong><small>Recalculate and clear blockers</small></span></div><div className={run.status === "review" ? "current" : ["approved", "paid"].includes(run.status) ? "done" : ""}><i>2</i><span><strong>Finance review</strong><small>Maker submits a clean snapshot</small></span></div><div className={run.status === "approved" ? "current" : run.status === "paid" ? "done" : ""}><i>3</i><span><strong>Owner approval</strong><small>Snapshot becomes immutable</small></span></div><div className={run.status === "paid" ? "done current" : ""}><i>4</i><span><strong>Paid</strong><small>Payout completed</small></span></div></section>
    <section className="wf-finance-panel"><header><div><span>Payout register</span><h2>Associate payroll items</h2><p>Open an associate to inspect the frozen daily trace.</p></div></header><div className="table-wrap"><table className="wf-finance-table"><thead><tr><th>Associate</th><th>Station</th><th>Days</th><th>Shipments</th><th>Base</th><th>Incentive</th><th>Additions</th><th>Deductions</th><th>Net</th><th>Status</th><th>Control</th></tr></thead><tbody>
      {items.map((item) => <tr key={item.id}><td><PendingLink href={`/delivery-network/payroll/${run.id}?item=${item.id}`}><strong>{item.worker_name}</strong><small>{item.dropx_id} · {strings(item.provider_member_ids).join(", ") || "No provider ID"}</small><small>{maskedAccount(item.bank_account_no)} · {item.ifsc_code ?? "IFSC pending"}</small></PendingLink></td><td>{item.station_code ?? "-"}</td><td>{item.work_days}</td><td>{number(item.shipment_count)}</td><td>{money(item.base_amount)}</td><td>{money(item.incentive_amount)}</td><td>{money(item.adjustment_amount)}</td><td>{money(item.deduction_amount)}</td><td><strong>{money(item.net_amount)}</strong></td><td><span className={`wf-pay-state ${item.status}`}>{item.status}</span>{strings(item.hold_reasons).length ? <small>{strings(item.hold_reasons).join(" · ")}</small> : null}</td><td>{run.status === "draft" && canEdit && ["hold", "excluded"].includes(item.status) ? <form action={setPayrollItemDisposition}><input name="run_id" type="hidden" value={run.id} /><input name="item_id" type="hidden" value={item.id} /><input name="disposition" type="hidden" value={item.status === "excluded" ? "restore" : "exclude"} /><SubmitButton confirmationBlocked={false} confirmMessage={item.status === "excluded" ? "Restore this associate to the payroll run?" : "Exclude this held associate from the payable run? Accrued earnings remain visible."} pendingText="Updating">{item.status === "excluded" ? "Restore" : "Exclude"}</SubmitButton></form> : "-"}</td></tr>)}
    </tbody></table></div></section>
    <div className="wf-payroll-bottom-grid"><section className="wf-finance-panel"><header><div><span>Lifecycle audit</span><h2>Run events</h2></div></header><div className="wf-event-list">{events.map((event) => <article key={event.id}><i /><div><strong>{words(event.event_code)}</strong><span>{event.from_status ? `${event.from_status} → ` : ""}{event.to_status ?? ""}</span><small>{new Date(event.created_at).toLocaleString("en-IN")}{event.remarks ? ` · ${event.remarks}` : ""}</small></div></article>)}</div></section><section className="wf-finance-panel"><header><div><span>Approval controls</span><h2>Next action</h2></div></header><div className="wf-run-actions">
      {run.status === "draft" && canEdit ? <form action={changePayrollRunStatus}><input name="id" type="hidden" value={run.id} /><input name="action" type="hidden" value="submit" /><p>Submission is blocked until holds and source exceptions are zero.</p><SubmitButton confirmationBlocked={run.hold_count > 0 || run.exception_count > 0} confirmMessage={run.hold_count || run.exception_count ? `Clear ${run.hold_count} holds and ${run.exception_count} exceptions first.` : "Submit this payroll snapshot for finance review?"} pendingText="Submitting"><Send size={14} /> Submit for review</SubmitButton></form> : null}
      {run.status === "review" && canApprove ? <form action={changePayrollRunStatus}><input name="id" type="hidden" value={run.id} /><input name="action" type="hidden" value="approve" /><label>Approval remarks<textarea name="remarks" placeholder="Optional owner approval note" rows={3} /></label><SubmitButton confirmationBlocked={false} confirmMessage={`Approve ${money(run.net_amount)} for payout? The snapshot becomes immutable.`} pendingText="Approving"><CheckCircle2 size={14} /> Approve payroll</SubmitButton></form> : null}
      {run.status === "review" && owner ? <form action={changePayrollRunStatus}><input name="id" type="hidden" value={run.id} /><input name="action" type="hidden" value="return" /><label>Correction reason<textarea name="remarks" required /></label><SubmitButton pendingText="Returning">Return for correction</SubmitButton></form> : null}
      {run.status === "review" && owner && !canApprove ? <p>You submitted this payroll. Maker-checker control requires another company owner to approve it.</p> : null}
      {run.status === "approved" && owner ? <form action={changePayrollRunStatus}><input name="id" type="hidden" value={run.id} /><input name="action" type="hidden" value="paid" /><label>Payment reference<input name="payment_reference" required placeholder="Bank transfer / payout batch reference" /></label><label>Payment date<input name="payment_date" required type="date" /></label><SubmitButton confirmationBlocked={false} confirmMessage={`Confirm ${money(run.net_amount)} was paid?`} pendingText="Marking paid">Mark paid</SubmitButton></form> : null}
      {["draft", "review"].includes(run.status) && owner ? <form action={changePayrollRunStatus}><input name="id" type="hidden" value={run.id} /><input name="action" type="hidden" value="cancel" /><SubmitButton confirmationBlocked={false} confirmMessage="Cancel this payroll run? Posted adjustments will return to the approval pool." pendingText="Cancelling">Cancel run</SubmitButton></form> : null}
      {run.status === "paid" ? <div className="wf-paid-callout"><CheckCircle2 size={22} /><strong>Payroll completed</strong><span>{run.paid_at ? new Date(run.paid_at).toLocaleString("en-IN") : "Paid"}</span></div> : null}
    </div></section></div>
    {selectedItem ? <div className="modal-backdrop"><section className="modal-panel wide wf-finance-modal"><header><div><span>Frozen calculation trace</span><h2>{selectedItem.worker_name}</h2><p>{selectedItem.dropx_id} · {selectedItem.station_code} · {money(selectedItem.net_amount)}</p></div><PendingLink aria-label="Close" href={`/delivery-network/payroll/${run.id}`}>×</PendingLink></header><div className="table-wrap"><table className="wf-finance-table"><thead><tr><th>Date</th><th>Source</th><th>Provider ID</th><th>Shipments</th><th>Base</th><th>Incentive</th><th>Adjustment</th><th>Net</th></tr></thead><tbody>{lines.map((line) => <tr key={line.id}><td>{line.work_date}</td><td>{words(line.calculation_source)}<small>{line.provider_name ?? words(line.source_type)}</small></td><td>{line.provider_member_id ?? "-"}</td><td>{number(line.shipment_count)}</td><td>{money(line.base_amount)}</td><td>{money(line.incentive_amount)}</td><td>{money(line.adjustment_amount)}</td><td><strong>{money(line.net_amount)}</strong></td></tr>)}</tbody></table></div></section></div> : null}
  </AppShell>;
}
