import {supabaseAdmin as db} from "@/lib/supabase-admin";
import {savePartnerDigestSetting} from "@/app/delivery-network/amazon-onboarding-settings/actions";
import {SubmitButton} from "./submit-button";
export async function PartnerDigestMaster({companyId,canEdit}:{companyId:string;canEdit:boolean}){
 if(!db)return null;
 const [settings,stations,users,history]=await Promise.all([
 db.from("workforce_partner_digest_settings").select("*").eq("company_id",companyId),
 db.from("stations").select("id,station_code,station_email,station_manager_email,cluster_manager_email").eq("company_id",companyId).eq("is_active",true).order("station_code"),
 db.from("profiles").select("id,full_name,email").eq("company_id",companyId).eq("is_active",true).order("full_name"),
 db.from("workforce_partner_digest_deliveries").select("id,station_id,report_date,status,error_message,recipients").eq("company_id",companyId).order("created_at",{ascending:false}).limit(30)
 ]);
 const error=[settings,stations,users,history].find(r=>r.error)?.error;if(error)return <p role="alert">Email follow-up configuration unavailable: {error.message}</p>;
 const form=(setting:any)=><form action={savePartnerDigestSetting} className="form-grid"><input type="hidden" name="id" value={setting?.id||""}/><input type="hidden" name="version" value={setting?.updated_at||""}/><fieldset disabled={!canEdit} style={{display:"contents",border:0}}><label>Station<select name="station_id" defaultValue={setting?.station_id||""} required><option value="">Select station</option>{stations.data?.map(s=><option key={s.id} value={s.id}>{s.station_code}</option>)}</select></label>{[['workforce_user_ids','Workforce team'],['ops_user_ids','Ops team'],['recruit_user_ids','Recruitment team']].map(([key,label])=><label key={key}>{label}<select name={key} multiple defaultValue={setting?.[key]||[]} size={4}>{users.data?.map(u=><option key={u.id} value={u.id}>{u.full_name} · {u.email}</option>)}</select></label>)}<label>Daily send hour (IST)<input type="number" min="0" max="23" name="send_hour" required defaultValue={setting?.send_hour??9}/></label>{[['include_station','Station mailbox'],['include_station_manager','Station manager'],['include_cluster_manager','Cluster manager']].map(([key,label])=><label className="checkbox-row" key={key}><input type="checkbox" name={key} defaultChecked={setting?.[key]??true}/>{label} from Station master</label>)}<label className="checkbox-row"><input type="checkbox" name="is_active" defaultChecked={setting?.is_active??false}/>Send daily station follow-up</label><SubmitButton pendingText="Saving">{setting?'Save email rule':'Add station email rule'}</SubmitButton></fieldset></form>;
 return <section className="panel"><div className="panel-head"><div><h2>Daily team follow-up</h2><p className="subtle">One daily email thread per station.</p></div></div><div className="panel-body"><details><summary style={{cursor:"pointer",fontWeight:600}}>Add station email rule</summary><p className="subtle">Combines overdue invitations and pending IDs. Station and cluster addresses come from Station master; a recipient change starts a new thread.</p>{form(null)}</details>{settings.data?.map(s=><details key={s.id}><summary>{stations.data?.find(x=>x.id===s.station_id)?.station_code} · {s.is_active?'Enabled':'Paused'}</summary>{form(s)}</details>)}<h3>Recent email delivery</h3>{history.data?.length?<table><thead><tr><th>Station</th><th>Date</th><th>Result</th></tr></thead><tbody>{history.data.map(h=><tr key={h.id}><td>{stations.data?.find(s=>s.id===h.station_id)?.station_code}</td><td>{h.report_date}</td><td>{h.status}<small>{h.error_message}</small></td></tr>)}</tbody></table>:<p>No follow-up emails have been sent yet.</p>}</div></section>;
}
