import { ArrowRight, Gift, PauseCircle, PlayCircle, Plus, Target } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PendingLink } from "@/components/pending-link";
import { SubmitButton } from "@/components/submit-button";
import { hasPermission, requirePagePermission } from "@/lib/authorization";
import { requireCompanyId } from "@/lib/company-scope";
import { firstDesignationBusinessCategory } from "@/lib/designation-business-categories";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { workforceToday } from "@/lib/workforce-earnings";
import { changeIncentiveStatus, createIncentiveCampaign } from "./actions";

export const dynamic = "force-dynamic";

type Campaign = { id: string; code: string; name: string; provider_id: string | null; station_id: string | null; designation_id: string | null; metric: string; calculation_type: string; threshold_value: number; rate_value: number; flat_amount: number; maximum_amount: number | null; effective_from: string; effective_to: string; status: string; description: string | null };
function money(value: unknown) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(Number(value ?? 0)); }
function title(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }

export default async function IncentivesPage({ searchParams }: { searchParams?: { add?: string; notice?: string; error?: string } }) {
  const authorization = await requirePagePermission("workforce_incentives", "access");
  const companyId = requireCompanyId(authorization);
  const permission = authorization.permissions.workforce_incentives;
  const canAdd = permission.canAdd && !authorization.readOnly;
  const [campaignResult, providerResult, stationResult, designationResult] = supabaseAdmin ? await Promise.all([
    supabaseAdmin.from("workforce_incentive_campaigns").select("id, code, name, provider_id, station_id, designation_id, metric, calculation_type, threshold_value, rate_value, flat_amount, maximum_amount, effective_from, effective_to, status, description").eq("company_id", companyId).order("effective_from", { ascending: false }),
    supabaseAdmin.from("providers").select("id, code, name").eq("company_id", companyId).order("name"),
    supabaseAdmin.from("stations").select("id, station_code, station_name").eq("company_id", companyId).eq("is_active", true).order("station_code"),
    supabaseAdmin.from("designations").select("id, code, name, designation_category:designation_categories!designations_designation_category_id_fkey(id, code, name, people_module, is_active)").eq("company_id", companyId).eq("is_active", true).order("name")
  ]) : [{ data: [], error: { message: "Supabase service role key is not configured." } }, { data: [], error: null }, { data: [], error: null }, { data: [], error: null }];
  const campaigns = ((campaignResult.data ?? []) as Campaign[]).filter((campaign) => authorization.hasAllLocationAccess || !campaign.station_id || authorization.locationScopeIds.includes(campaign.station_id));
  const providers = providerResult.data ?? [];
  const allStations = stationResult.data ?? [];
  const stations = authorization.hasAllLocationAccess ? allStations : allStations.filter((station) => authorization.locationScopeIds.includes(station.id));
  const designations = (designationResult.data ?? []).filter((designation) => firstDesignationBusinessCategory(designation.designation_category)?.people_module === "delivery_network");
  const error = campaignResult.error?.message ?? providerResult.error?.message ?? stationResult.error?.message ?? designationResult.error?.message ?? null;
  const providerById = new Map(providers.map((provider) => [provider.id, provider]));
  const stationById = new Map(stations.map((station) => [station.id, station]));
  const designationById = new Map(designations.map((designation) => [designation.id, designation]));

  return <AppShell active="Incentives" pageCode="workforce_incentives">
    <section className="wf-finance-hero compact"><div><span>Rewards engine</span><h1>Incentive campaigns</h1><p>Roll out daily shipment targets for a provider, station or designation and watch rewards flow into live earnings automatically.</p></div><div className="wf-finance-actions">{hasPermission(authorization, "workforce_earnings", "access") ? <PendingLink className="wf-command-secondary" href="/delivery-network/earnings">View live impact</PendingLink> : null}{canAdd ? <PendingLink className="wf-command-primary" href="/delivery-network/incentives?add=1"><Plus size={16} /> New campaign</PendingLink> : null}</div></section>
    {searchParams?.notice || searchParams?.error ? <section className={`panel message-panel ${searchParams.error ? "error" : "success"}`}><div className="panel-body"><strong>{searchParams.error ? "Action required" : "Completed"}</strong><p>{searchParams.error ?? searchParams.notice}</p></div></section> : null}
    {error ? <section className="panel message-panel error"><div className="panel-body"><strong>Incentive storage is not ready</strong><p>{error}</p></div></section> : null}
    <section className="wf-finance-kpis mini"><article><span><Gift size={18} /></span><small>Total campaigns</small><strong>{campaigns.length}</strong><em>All versions</em></article><article><span><PlayCircle size={18} /></span><small>Active now</small><strong>{campaigns.filter((campaign) => campaign.status === "active").length}</strong><em>Included in earnings</em></article><article><span><PauseCircle size={18} /></span><small>Draft / paused</small><strong>{campaigns.filter((campaign) => ["draft", "paused"].includes(campaign.status)).length}</strong><em>No future accrual</em></article></section>
    <section className="wf-finance-panel"><header><div><span>Campaign registry</span><h2>Target and reward rules</h2><p>Multiple active campaigns can stack when their scopes match.</p></div>{hasPermission(authorization, "workforce_earnings", "access") ? <PendingLink href="/delivery-network/earnings?view=trace">Open calculation trace <ArrowRight size={14} /></PendingLink> : null}</header><div className="table-wrap"><table className="wf-finance-table"><thead><tr><th>Campaign</th><th>Scope</th><th>Metric &amp; threshold</th><th>Reward</th><th>Period</th><th>Status</th><th>Action</th></tr></thead><tbody>
      {campaigns.map((campaign) => { const canManage = permission.canEdit && !authorization.readOnly && (authorization.hasAllLocationAccess || Boolean(campaign.station_id && authorization.locationScopeIds.includes(campaign.station_id))); return <tr key={campaign.id}><td><strong>{campaign.name}</strong><small>{campaign.code} · {campaign.description ?? "No description"}</small></td><td>{campaign.provider_id ? providerById.get(campaign.provider_id)?.name ?? "Provider" : "All providers"}<small>{campaign.station_id ? stationById.get(campaign.station_id)?.station_code ?? "Scoped station" : "All stations"} · {campaign.designation_id ? designationById.get(campaign.designation_id)?.name ?? "Scoped designation" : "All designations"}</small></td><td>{title(campaign.metric)}<small>Threshold {campaign.threshold_value}</small></td><td>{campaign.calculation_type === "flat_threshold" ? money(campaign.flat_amount) : `${money(campaign.rate_value)} per unit above`}<small>{campaign.maximum_amount ? `Cap ${money(campaign.maximum_amount)}` : "No cap"}</small></td><td>{campaign.effective_from}<small>to {campaign.effective_to}</small></td><td><span className={`wf-pay-state ${campaign.status}`}>{campaign.status}</span></td><td>{canManage && campaign.status !== "closed" ? <div className="wf-row-actions"><form action={changeIncentiveStatus}><input name="id" type="hidden" value={campaign.id} /><input name="status" type="hidden" value={campaign.status === "active" ? "paused" : "active"} /><SubmitButton pendingText="Saving">{campaign.status === "active" ? "Pause" : "Activate"}</SubmitButton></form><form action={changeIncentiveStatus}><input name="id" type="hidden" value={campaign.id} /><input name="status" type="hidden" value="closed" /><SubmitButton confirmationBlocked={false} confirmMessage="Close this campaign permanently?" pendingText="Closing">Close</SubmitButton></form></div> : "-"}</td></tr>; })}
      {!campaigns.length && !error ? <tr><td className="empty-cell" colSpan={7}>No incentive campaigns have been created.</td></tr> : null}
    </tbody></table></div></section>
    {searchParams?.add && canAdd ? <div className="modal-backdrop"><section className="modal-panel wide wf-finance-modal"><header><div><span>Reward rollout</span><h2>Create incentive campaign</h2><p>Campaigns begin as drafts and affect earnings only after activation.</p></div><PendingLink aria-label="Close" href="/delivery-network/incentives">×</PendingLink></header><form action={createIncentiveCampaign} className="wf-finance-form">
      <label>Campaign code<input name="code" placeholder="ONAM_30_PLUS" required /></label><label className="span-2">Campaign name<input name="name" placeholder="Onam 30+ delivery sprint" required /></label>
      <label>Provider scope<select name="provider_id"><option value="">All providers</option>{providers.map((provider) => <option key={provider.id} value={provider.id}>{provider.code} · {provider.name}</option>)}</select></label><label>Station scope<select name="station_id" required={!authorization.hasAllLocationAccess}>{authorization.hasAllLocationAccess ? <option value="">All stations</option> : <option value="">Choose station</option>}{stations.map((station) => <option key={station.id} value={station.id}>{station.station_code} · {station.station_name}</option>)}</select></label><label>Designation scope<select name="designation_id"><option value="">All designations</option>{designations.map((designation) => <option key={designation.id} value={designation.id}>{designation.code} · {designation.name}</option>)}</select></label>
      <label>Production metric<select name="metric"><option value="total_delivery">Total delivery</option><option value="total_activity">Total activity</option><option value="amazon_delivery">Amazon delivery</option><option value="swa_delivery">SWA delivery</option><option value="c_return">Customer return</option><option value="mfn">MFN</option></select></label><label>Reward type<select name="calculation_type"><option value="flat_threshold">Flat reward on reaching threshold</option><option value="per_unit_above_threshold">Per unit above threshold</option></select></label>
      <label>Daily threshold<input min="0" name="threshold_value" required step="1" type="number" /></label><label>Flat reward<input defaultValue="0" min="0" name="flat_amount" step="0.01" type="number" /></label><label>Per-unit reward<input defaultValue="0" min="0" name="rate_value" step="0.01" type="number" /></label><label>Maximum per day<input min="0" name="maximum_amount" placeholder="No cap" step="0.01" type="number" /></label>
      <label>Effective from<input defaultValue={workforceToday()} name="effective_from" required type="date" /></label><label>Effective to<input name="effective_to" required type="date" /></label><label className="span-2">Description<textarea name="description" placeholder="Eligibility, client approval, communication reference" rows={3} /></label>
      <div className="wf-form-actions span-2"><PendingLink href="/delivery-network/incentives">Cancel</PendingLink><SubmitButton pendingText="Creating draft"><Target size={15} /> Create draft campaign</SubmitButton></div>
    </form></section></div> : null}
  </AppShell>;
}
