import { ArrowDownCircle, ArrowRight, ArrowUpCircle, CheckCircle2, Clock3, Plus } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PendingLink } from "@/components/pending-link";
import { SubmitButton } from "@/components/submit-button";
import { hasPermission, isCompanyOwner, requirePagePermission } from "@/lib/authorization";
import { requireCompanyId } from "@/lib/company-scope";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { workforceToday } from "@/lib/workforce-earnings";
import { createWorkforceAdjustment, reviewWorkforceAdjustment } from "./actions";

export const dynamic = "force-dynamic";
type Adjustment = { id: string; workforce_id: string; adjustment_type: string; category: string; amount: number; effective_date: string; reason: string; external_reference: string | null; status: string; requested_by: string | null; requested_at: string; review_remarks: string | null };
type Worker = { id: string; dropx_id: string | null; full_name: string; location_id: string; stations?: { station_code?: string; station_name?: string | null } | null };
function money(value: unknown) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(Number(value ?? 0)); }
function title(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }

export default async function AdjustmentsPage({ searchParams }: { searchParams?: { add?: string; notice?: string; error?: string } }) {
  const authorization = await requirePagePermission("workforce_adjustments", "access");
  const companyId = requireCompanyId(authorization);
  const permission = authorization.permissions.workforce_adjustments;
  const canAdd = permission.canAdd && !authorization.readOnly;
  let adjustmentQuery = supabaseAdmin?.from("workforce_adjustments").select("id, workforce_id, adjustment_type, category, amount, effective_date, reason, external_reference, status, requested_by, requested_at, review_remarks").eq("company_id", companyId).order("requested_at", { ascending: false }).limit(1000);
  let workerQuery = supabaseAdmin?.from("workforce").select("id, dropx_id, full_name, location_id, stations:stations!workforce_location_id_fkey(station_code, station_name)").eq("company_id", companyId).is("deleted_at", null).neq("migration_state", "reclassified").order("full_name");
  if (workerQuery && !authorization.hasAllLocationAccess) workerQuery = workerQuery.in("location_id", authorization.locationScopeIds.length ? authorization.locationScopeIds : ["00000000-0000-0000-0000-000000000000"]);
  const [adjustmentResult, workerResult] = adjustmentQuery && workerQuery ? await Promise.all([adjustmentQuery, workerQuery]) : [{ data: [], error: { message: "Supabase service role key is not configured." } }, { data: [], error: null }];
  const workers = (workerResult.data ?? []) as unknown as Worker[];
  const workerById = new Map(workers.map((worker) => [worker.id, worker]));
  const adjustments = ((adjustmentResult.data ?? []) as Adjustment[]).filter((adjustment) => workerById.has(adjustment.workforce_id));
  const error = adjustmentResult.error?.message ?? workerResult.error?.message ?? null;
  const pending = adjustments.filter((item) => item.status === "pending");
  const approvedEarnings = adjustments.filter((item) => ["approved", "posted"].includes(item.status) && item.adjustment_type === "earning").reduce((sum, item) => sum + Number(item.amount), 0);
  const approvedDeductions = adjustments.filter((item) => ["approved", "posted"].includes(item.status) && item.adjustment_type === "deduction").reduce((sum, item) => sum + Number(item.amount), 0);

  return <AppShell active="Ad hoc Adjustments" pageCode="workforce_adjustments">
    <section className="wf-finance-hero compact"><div><span>Exception payments</span><h1>Ad hoc earnings &amp; deductions</h1><p>Capture ID exceptions, one-time bonuses, reimbursements and recoveries with maker-checker approval and payroll traceability.</p></div><div className="wf-finance-actions">{hasPermission(authorization, "workforce_earnings", "access") ? <PendingLink className="wf-command-secondary" href="/delivery-network/earnings">Live earnings</PendingLink> : null}{canAdd ? <PendingLink className="wf-command-primary" href="/delivery-network/adjustments?add=1"><Plus size={16} /> New adjustment</PendingLink> : null}</div></section>
    {searchParams?.notice || searchParams?.error ? <section className={`panel message-panel ${searchParams.error ? "error" : "success"}`}><div className="panel-body"><strong>{searchParams.error ? "Action required" : "Completed"}</strong><p>{searchParams.error ?? searchParams.notice}</p></div></section> : null}
    {error ? <section className="panel message-panel error"><div className="panel-body"><strong>Adjustment storage is not ready</strong><p>{error}</p></div></section> : null}
    <section className="wf-finance-kpis mini"><article><span><Clock3 size={18} /></span><small>Pending approval</small><strong>{pending.length}</strong><em>Owner decision required</em></article><article><span><ArrowUpCircle size={18} /></span><small>Approved additions</small><strong>{money(approvedEarnings)}</strong><em>Included by effective date</em></article><article><span><ArrowDownCircle size={18} /></span><small>Approved deductions</small><strong>{money(approvedDeductions)}</strong><em>Included by effective date</em></article></section>
    <section className="wf-finance-panel"><header><div><span>Adjustment ledger</span><h2>Maker-checker queue</h2><p>Approved rows enter live earnings and the next matching payroll snapshot exactly once.</p></div>{hasPermission(authorization, "workforce_payroll", "access") ? <PendingLink href="/delivery-network/payroll">Open payroll <ArrowRight size={14} /></PendingLink> : null}</header><div className="table-wrap"><table className="wf-finance-table"><thead><tr><th>Associate</th><th>Effective date</th><th>Type</th><th>Category</th><th>Amount</th><th>Reason / reference</th><th>Status</th><th>Review</th></tr></thead><tbody>
      {adjustments.map((adjustment) => { const worker = workerById.get(adjustment.workforce_id)!; const canReview = adjustment.status === "pending" && adjustment.requested_by !== authorization.userId && isCompanyOwner(authorization) && permission.canEdit && !authorization.readOnly; return <tr key={adjustment.id}><td><strong>{worker.full_name}</strong><small>{worker.dropx_id ?? "No DropX ID"} · {worker.stations?.station_code ?? "-"}</small></td><td>{adjustment.effective_date}</td><td><span className={`wf-pay-state ${adjustment.adjustment_type}`}>{adjustment.adjustment_type}</span></td><td>{title(adjustment.category)}</td><td><strong>{money(adjustment.amount)}</strong></td><td>{adjustment.reason}<small>{adjustment.external_reference ?? "No external reference"}</small></td><td><span className={`wf-pay-state ${adjustment.status}`}>{adjustment.status}</span>{adjustment.review_remarks ? <small>{adjustment.review_remarks}</small> : null}</td><td>{canReview ? <div className="wf-review-stack"><form action={reviewWorkforceAdjustment}><input name="id" type="hidden" value={adjustment.id} /><input name="decision" type="hidden" value="approved" /><input name="review_remarks" placeholder="Approval note" /><SubmitButton pendingText="Approving"><CheckCircle2 size={13} /> Approve</SubmitButton></form><form action={reviewWorkforceAdjustment}><input name="id" type="hidden" value={adjustment.id} /><input name="decision" type="hidden" value="rejected" /><input name="review_remarks" placeholder="Rejection reason" required /><SubmitButton pendingText="Rejecting">Reject</SubmitButton></form></div> : adjustment.status === "pending" && adjustment.requested_by === authorization.userId ? <small>Awaiting another owner</small> : "-"}</td></tr>; })}
      {!adjustments.length && !error ? <tr><td className="empty-cell" colSpan={8}>No ad hoc adjustments have been created.</td></tr> : null}
    </tbody></table></div></section>
    {searchParams?.add && canAdd ? <div className="modal-backdrop"><section className="modal-panel wide wf-finance-modal"><header><div><span>Controlled exception</span><h2>Create payroll adjustment</h2><p>This request remains outside payable earnings until the company owner approves it.</p></div><PendingLink aria-label="Close" href="/delivery-network/adjustments">×</PendingLink></header><form action={createWorkforceAdjustment} className="wf-finance-form">
      <label className="span-2">Workforce associate<select name="workforce_id" required><option value="">Choose associate</option>{workers.map((worker) => <option key={worker.id} value={worker.id}>{worker.dropx_id ?? "No ID"} · {worker.full_name} · {worker.stations?.station_code ?? "-"}</option>)}</select></label><label>Adjustment type<select name="adjustment_type"><option value="earning">Earning / addition</option><option value="deduction">Deduction / recovery</option></select></label><label>Category<select name="category"><option value="id_exception">ID exception payment</option><option value="delivery_correction">Delivery correction</option><option value="joining_bonus">Joining bonus</option><option value="referral_bonus">Referral bonus</option><option value="reimbursement">Reimbursement</option><option value="asset_recovery">Asset recovery</option><option value="cash_recovery">Cash recovery</option><option value="other">Other</option></select></label><label>Amount<input min="0.01" name="amount" required step="0.01" type="number" /></label><label>Effective date<input defaultValue={workforceToday()} name="effective_date" required type="date" /></label><label className="span-2">Reason<textarea name="reason" placeholder="Explain the exception and evidence" required rows={3} /></label><label className="span-2">External reference<input name="external_reference" placeholder="Ticket, email, provider case or UTR reference" /></label><div className="wf-form-actions span-2"><PendingLink href="/delivery-network/adjustments">Cancel</PendingLink><SubmitButton pendingText="Submitting">Submit for approval</SubmitButton></div>
    </form></section></div> : null}
  </AppShell>;
}
