import Link from 'next/link';
import {AppShell} from '@/components/app-shell';
import {SearchableSelect} from '@/components/searchable-select';
import {SubmitButton} from '@/components/submit-button';
import {requirePagePermission,hasPermission,isCompanyOwner} from '@/lib/authorization';
import {requireCompanyId} from '@/lib/company-scope';
import {supabaseAdmin} from '@/lib/supabase-admin';
import {readAllRows} from '@/lib/supabase-pagination';
import {workforceClassification} from '@/lib/workforce-classification';
import {createPooledPolicy,acceptPooledAgreement,submitPooledSettlement,reviewPooledSettlement} from './actions';
import styles from '@/components/workforce-mileage-desk.module.css';
export const dynamic='force-dynamic';
type Search={agreement?:string;station?:string;status?:string;q?:string;sort?:string;page?:string;error?:string;notice?:string};
type Person={id:string;full_name:string;dropx_id:string|null;location_id:string;onboarding_status:string;designation_id:string|null;designation:string|null};
type Station={id:string;station_code:string};
type Policy={id:string;station_id:string;name:string;formula:string;daily_guarantee:number;packages_per_day:number;package_rate:number;effective_from:string;effective_to:string;policy_reference:string;created_by:string;created_at:string};
type Agreement={id:string;station_id:string;workforce_id:string;policy_id:string;window_start:string;window_end:string;accepted_on:string;acceptance_reference:string;created_by:string;created_at:string};
type Snapshot={fingerprint:string;from:string;to:string;formula:string;qualifyingDays:number;packages:number;packageAllowance:number;baseAlreadyInPayroll:number;supplement:number;combinedEntitlement:number;days:{date:string;packages:number;base:number;activity:number}[]};
type Settlement={id:string;agreement_id:string;station_id:string;workforce_id:string;reference:string;posting_date:string;snapshot:Snapshot;supplemental_amount:number;status:string;requested_by:string;requested_at:string;reviewed_by:string|null;reviewed_at:string|null;review_note:string|null;adjustment:{status:string;payroll_run_id:string|null}|null};
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(n));
const time=(s:string)=>new Date(s).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'});
const formula=(s:string)=>s==='pooled_floor'?'Higher of guarantee or package earnings':'Guarantee + packages above pooled allowance';
export default async function PooledPage({searchParams:params={}}:{searchParams?:Search}){
 const auth=await requirePagePermission('workforce_adjustments','access'),company=requireCompanyId(auth),none='00000000-0000-0000-0000-000000000000';
 let error='',previewError='',people:Person[]=[],stations:Station[]=[],policies:Policy[]=[],agreements:Agreement[]=[],settlements:Settlement[]=[],preview:Snapshot|null=null;
 const actors=new Map<string,string>();
 try{
  if(!supabaseAdmin)throw new Error('Database is unavailable.');
  let pq=supabaseAdmin.from('workforce').select('id,full_name,dropx_id,location_id,onboarding_status,designation_id,designation').eq('company_id',company).is('deleted_at',null).neq('migration_state','reclassified').order('full_name').order('id');
  let sq=supabaseAdmin.from('stations').select('id,station_code').eq('company_id',company).order('station_code').order('id');
  let pol=supabaseAdmin.from('workforce_pooled_policies').select('*').eq('company_id',company).order('effective_from',{ascending:false}).order('id');
  let ag=supabaseAdmin.from('workforce_pooled_agreements').select('*').eq('company_id',company).order('window_end',{ascending:false}).order('id');
  let st=supabaseAdmin.from('workforce_pooled_settlements').select('*,adjustment:workforce_adjustments(status,payroll_run_id)').eq('company_id',company).order('requested_at',{ascending:false}).order('id');
  if(!auth.hasAllLocationAccess){const scope=auth.locationScopeIds.length?auth.locationScopeIds:[none];pq=pq.in('location_id',scope);sq=sq.in('id',scope);pol=pol.in('station_id',scope);ag=ag.in('station_id',scope);st=st.in('station_id',scope);}
  const [p,s,po,a,se,eligible]=await Promise.all([readAllRows(pq),readAllRows(sq),readAllRows(pol),readAllRows(ag),readAllRows(st),workforceClassification(company)]);
  if([p,s,po,a,se].some(r=>r.error))throw new Error('Pooled settlement records could not be loaded. No changes were made. Please retry.');
  people=(p.data??[]).filter(eligible) as Person[];stations=s.data??[];policies=po.data??[];agreements=a.data??[];
  settlements=(se.data??[]).map(r=>({...r,adjustment:Array.isArray(r.adjustment)?r.adjustment[0]:r.adjustment})) as Settlement[];
  const ids=[...new Set([...policies.map(p=>p.created_by),...agreements.map(a=>a.created_by),...settlements.flatMap(s=>[s.requested_by,s.reviewed_by])].filter((s):s is string=>Boolean(s)))];
  for(let n=0;n<ids.length;n+=100){const result=await supabaseAdmin.from('profiles').select('id,full_name').eq('company_id',company).in('id',ids.slice(n,n+100));for(const row of result.data??[])actors.set(row.id,row.full_name??row.id);}
  if(params.agreement){if(!agreements.some(a=>a.id===params.agreement))previewError='Select an accepted window within your station scope.';else{const result=await supabaseAdmin.rpc('workforce_calculate_pooled_window',{p_company:company,p_agreement:params.agreement,p_locations:auth.hasAllLocationAccess?null:auth.locationScopeIds});if(result.error)previewError=result.error.message;else preview=result.data as Snapshot;}}
 }catch(e){error=e instanceof Error?e.message:'Unable to load settlements.';}
 const stationName=new Map(stations.map(s=>[s.id,s.station_code])),person=new Map(people.map(p=>[p.id,p]));
 const canConfigure=!error&&!auth.readOnly&&isCompanyOwner(auth)&&hasPermission(auth,'workforce_rate_cards','edit');
 const canSubmit=!error&&!auth.readOnly&&hasPermission(auth,'workforce_adjustments','add'),canReview=!error&&!auth.readOnly&&isCompanyOwner(auth)&&hasPermission(auth,'workforce_adjustments','edit');
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const description=(a:Agreement)=>`${person.get(a.workforce_id)?.dropx_id??'Historical ID'} · ${person.get(a.workforce_id)?.full_name??'Historical associate'} · ${stationName.get(a.station_id)} · ${a.window_start}–${a.window_end}`;
 const query=(params.q??'').trim().toLowerCase();
 const filtered=settlements.filter(s=>(!params.status||s.status===params.status)&&(!params.station||s.station_id===params.station)&&(!query||[s.reference,person.get(s.workforce_id)?.full_name,person.get(s.workforce_id)?.dropx_id].some(v=>v?.toLowerCase().includes(query))));if(params.sort==='oldest')filtered.reverse();
 const pages=Math.max(1,Math.ceil(filtered.length/25)),page=Math.min(pages,Math.max(1,Number.parseInt(params.page??'1',10)||1)),shown=filtered.slice((page-1)*25,page*25);
 const href=(n:number)=>{const q=new URLSearchParams();for(const k of ['station','status','q','sort'] as const)if(params[k])q.set(k,params[k]!);q.set('page',String(n));return '/delivery-network/pooled-settlements?'+q;};
 return <AppShell active="Pooled MG Settlement" pageCode="workforce_adjustments"><div className={styles.desk}>
  <header className={styles.header}><h1>Pooled MG settlement</h1><p>Close an associate’s agreed earning window, reconcile confirmed daily guarantees, then release only the supplement through payroll and Finance. Daily, weekly or fortnightly payouts do not reset this window.</p></header>
  {params.error||params.notice?<p role="status" className={styles.notice}>{params.error||params.notice}</p>:null}{error?<p role="alert" className={styles.notice+' '+styles.error}>{error}</p>:null}
  <aside className={styles.notice}><strong>Confirmed-base settlement</strong><p>This desk does not create daily base pay. First configure a matching fixed-daily rate card with no included fuel, then confirm all production payroll for the agreed window. Days without delivery source records, training pay, incentives and verified mileage are separate. Missing or changed source data blocks settlement.</p><Link href="/delivery-network/rate-cards">Rate cards</Link> · <Link href="/delivery-network/mileage">Mileage claims</Link> · <Link href="/delivery-network/payroll">Payroll</Link></aside>
  <section className={styles.panel}><h2>1. Station terms</h2><p>Save only agreed terms. Policy versions and accepted windows cannot be edited or overlapped.</p>
   {canConfigure?<details open={!policies.length}><summary>Create approved station policy</summary><form action={createPooledPolicy} className={styles.form}>
    <label>Station<select name="station_id" defaultValue="" required><option value="">Choose station</option>{stations.map(s=><option key={s.id} value={s.id}>{s.station_code}</option>)}</select></label>
    <label>Policy name / version<input name="name" required minLength={3} maxLength={120}/></label>
    <label>Formula<select name="formula" defaultValue="" required><option value="">Choose agreed formula</option><option value="guarantee_plus_excess">Guarantee + excess packages</option><option value="pooled_floor">Higher of guarantee or package earnings</option></select></label>
    <label>Daily guarantee (₹)<input type="number" name="daily_guarantee" min="0.01" max="1000000" step="0.01" required/></label>
    <label>Packages included per qualifying day<input type="number" name="packages_per_day" min="0" max="100000" step="1" required/><small>For guarantee + excess only. Enter 0 for the higher-of formula.</small></label>
    <label>Package rate (₹)<input type="number" name="package_rate" min="0" max="1000000" step="0.01" required/></label>
    <label>Effective from<input type="date" name="effective_from" required/></label><label>Effective through<input type="date" name="effective_to" required/><small>Maximum 366 days per policy.</small></label>
    <label>Approved policy reference<input name="policy_reference" minLength={3} maxLength={1000} required/></label><div><SubmitButton pendingText="Saving terms" confirmTitle="Save immutable station terms?" confirmMessage="Check the approved amounts, formula, station and dates. This does not change rate cards or create earnings.">Save station terms</SubmitButton></div>
   </form></details>:null}
   {!policies.length&&!error?<p>No station policy configured. An owner must enter approved terms; no default rate is assigned to anyone.</p>:<details><summary>{policies.length} policy versions</summary><div className={styles.table}><table><thead><tr><th>Station / policy</th><th>Formula / terms</th><th>Effective window</th><th>Reference / actor</th></tr></thead><tbody>{policies.map(p=><tr key={p.id}><td>{stationName.get(p.station_id)}<br/>{p.name}</td><td>{formula(p.formula)}<br/>{money(p.daily_guarantee)}/day · {p.packages_per_day} packages/day · {money(p.package_rate)}/package</td><td>{p.effective_from} → {p.effective_to}</td><td>{p.policy_reference}<br/>{actors.get(p.created_by)??p.created_by} · {time(p.created_at)} IST</td></tr>)}</tbody></table></div></details>}
  </section>
  <section className={styles.panel}><h2>2. Associate’s accepted window</h2><p>Use the actual agreement dates, not the payroll cycle. A complete window can contain multiple confirmed payroll runs.</p>
   {canConfigure&&policies.length?<details><summary>Record an accepted window</summary><form action={acceptPooledAgreement} className={styles.form}>
    <label>Station policy<select name="policy_id" defaultValue="" required><option value="">Choose station terms</option>{policies.map(p=><option key={p.id} value={p.id}>{stationName.get(p.station_id)} · {p.name} · {p.effective_from}–{p.effective_to}</option>)}</select></label>
    <label>Associate / DropX ID<SearchableSelect name="workforce_id" required placeholder="Search name, ID or station" options={people.filter(p=>p.onboarding_status==='active').map(p=>({value:p.id,label:(p.dropx_id??'ID pending')+' · '+p.full_name,helper:stationName.get(p.location_id)}))}/></label>
    <label>Window starts<input type="date" name="window_start" required/></label><label>Window ends<input type="date" name="window_end" required/><small>Maximum 93 days; no overlapping associate windows.</small></label>
    <label>Accepted on<input type="date" name="accepted_on" max={today} required/></label><label>Associate’s agreement reference<input name="acceptance_reference" minLength={3} maxLength={1000} required/></label>
    <div><SubmitButton pendingText="Saving agreement" confirmTitle="Record the accepted window?" confirmMessage="Confirm the associate accepted these station terms on or before the window start. The saved window cannot be changed.">Save accepted window</SubmitButton></div>
   </form></details>:null}
   <form method="get" className={styles.filters}><label>Calculate an accepted window<select name="agreement" defaultValue={params.agreement??''} required><option value="">Choose associate and window</option>{agreements.map(a=><option key={a.id} value={a.id}>{description(a)}</option>)}</select></label><button className="button secondary" disabled={!agreements.length||Boolean(error)}>Calculate closed window</button></form>
   {!agreements.length&&!error?<p>No accepted windows recorded yet.</p>:null}
   {agreements.length?<details><summary>Acceptance history</summary><div className={styles.table}><table><thead><tr><th>Associate / station / window</th><th>Accepted</th><th>Reference</th><th>Recorded by</th></tr></thead><tbody>{agreements.map(a=><tr key={a.id}><td>{description(a)}</td><td>{a.accepted_on}</td><td>{a.acceptance_reference}</td><td>{actors.get(a.created_by)??a.created_by}<br/>{time(a.created_at)} IST</td></tr>)}</tbody></table></div></details>:null}
   {previewError?<p role="alert" className={styles.notice+' '+styles.error}>{previewError}</p>:null}
   {preview?<article className={styles.claim}><h3>{preview.from} → {preview.to}</h3><p>{formula(preview.formula)}</p><dl className={styles.facts}><div><dt>Qualifying production days</dt><dd>{preview.qualifyingDays}</dd></div><div><dt>Packages / pooled allowance</dt><dd>{preview.packages} / {preview.formula==='pooled_floor'?'Not used':preview.packageAllowance}</dd></div><div><dt>Base already in confirmed payroll</dt><dd>{money(preview.baseAlreadyInPayroll)}</dd></div><div><dt>New supplement only</dt><dd><strong>{money(preview.supplement)}</strong></dd></div><div><dt>Combined base + supplement</dt><dd>{money(preview.combinedEntitlement)}</dd></div></dl>
    <details><summary>Daily reconciliation</summary><div className={styles.table}><table><thead><tr><th>Work date</th><th>Packages</th><th>Activities</th><th>Confirmed base</th></tr></thead><tbody>{preview.days.map(d=><tr key={d.date}><td>{d.date}</td><td>{d.packages}</td><td>{d.activity}</td><td>{money(d.base)}</td></tr>)}</tbody></table></div></details>
    {canSubmit&&!settlements.some(s=>s.agreement_id===params.agreement&&s.status!=='rejected')?<form action={submitPooledSettlement} className={styles.form}><input type="hidden" name="agreement_id" value={params.agreement}/><input type="hidden" name="fingerprint" value={preview.fingerprint}/><label>Open payroll posting date<input name="posting_date" type="date" defaultValue={today} required/><small>Must follow the window and must not be in a confirmed payroll period.</small></label><label>Unique settlement reference<input name="reference" required minLength={3} maxLength={180}/></label><label>Delivery source completeness<select name="source_complete" defaultValue="" required><option value="">Confirm after checking</option><option value="yes">All work for this window has been imported</option></select></label><div><p>{preview.supplement===0?'A reviewed zero supplement is recorded without creating a financial adjustment.':'Only the supplement is submitted. Base pay will not be duplicated.'}</p><SubmitButton pendingText="Submitting settlement" confirmTitle="Submit reconciled supplement?" confirmMessage="Confirm source completeness. A different owner must review it before any supplement enters payroll.">Submit for independent review</SubmitButton></div></form>:<p>This window already has a pending or approved settlement, or you have read-only access.</p>}
   </article>:null}
  </section>
  <section className={styles.panel}><h2>3. Settlement review &amp; history</h2><form key={JSON.stringify([params.q,params.station,params.status,params.sort])} method="get" className={styles.filters}><label>Search<input name="q" defaultValue={params.q??''} placeholder="Name, DropX ID or reference"/></label><label>Station<select name="station" defaultValue={params.station??''}><option value="">All accessible stations</option>{stations.map(s=><option key={s.id} value={s.id}>{s.station_code}</option>)}</select></label><label>Status<select name="status" defaultValue={params.status??''}><option value="">All statuses</option>{['pending','approved','rejected'].map(s=><option key={s}>{s}</option>)}</select></label><label>Sort<select name="sort" defaultValue={params.sort??'newest'}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></label><button className="button secondary">Apply</button><Link href="/delivery-network/pooled-settlements">Reset</Link></form><small>{filtered.length} matching settlements · all event times IST</small>
   <div className={styles.claims}>{shown.map(s=><article className={styles.claim} key={s.id}><div className={styles.claimHead}><div><h3>{person.get(s.workforce_id)?.full_name??'Historical associate'} · {money(s.supplemental_amount)}</h3><small>{person.get(s.workforce_id)?.dropx_id??s.workforce_id} · {stationName.get(s.station_id)} · {s.reference}</small></div><span className={styles.badge}>{s.status}</span></div>
    <dl className={styles.facts}><div><dt>Agreed window / posting</dt><dd>{s.snapshot.from} → {s.snapshot.to}<br/>Posting {s.posting_date}</dd></div><div><dt>Calculation</dt><dd>{s.snapshot.qualifyingDays} days · {s.snapshot.packages} packages<br/>Base {money(s.snapshot.baseAlreadyInPayroll)} + supplement {money(s.supplemental_amount)}</dd></div><div><dt>Requested by</dt><dd>{actors.get(s.requested_by)??s.requested_by}<br/>{time(s.requested_at)} IST</dd></div><div><dt>Independent review</dt><dd>{s.reviewed_at?<>{actors.get(s.reviewed_by??'')??s.reviewed_by}<br/>{time(s.reviewed_at)} IST</>:'Awaiting review'}</dd></div></dl><p>{formula(s.snapshot.formula)}</p>
    {s.review_note?<p><strong>Decision:</strong> {s.review_note}</p>:null}<p>{s.adjustment?.payroll_run_id?'Included in payroll '+s.adjustment.payroll_run_id+'. Payroll inclusion is not proof of payment.':Number(s.supplemental_amount)===0?'Zero supplement; no financial adjustment is created.':s.status==='approved'?'Approved supplement: recalculate the matching open payroll.':'Not a payable earning until approved.'}</p>
    <Link href={'/delivery-network/pooled-settlements?agreement='+s.agreement_id}>Recheck source calculation</Link>
    {canReview&&s.status==='pending'&&s.requested_by!==auth.userId?<form action={reviewPooledSettlement} className={styles.actions}><input type="hidden" name="settlement_id" value={s.id}/><label>Independent source / agreement verification notes<textarea name="review_note" minLength={10} maxLength={2000} required/></label><label>Decision<select name="decision" required defaultValue=""><option value="">Choose decision</option><option value="approved">Approve reconciliation</option><option value="rejected">Reject settlement</option></select></label><SubmitButton pendingText="Saving review" confirmTitle="Confirm independent decision?" confirmMessage="Check the original agreement, complete source records and confirmed base payroll. Approval is not a bank transfer.">Save review</SubmitButton></form>:s.status==='pending'&&s.requested_by===auth.userId?<p>A different authorised owner must review your submission.</p>:null}
   </article>)}</div>{!shown.length?<p>{error?'Settlement history is unavailable.':'No settlements match this view.'}</p>:null}{pages>1?<nav className={styles.pages} aria-label="Settlement history pages">{page>1?<Link href={href(page-1)}>Previous</Link>:null}<span>Page {page} of {pages}</span>{page<pages?<Link href={href(page+1)}>Next</Link>:null}</nav>:null}
  </section>
 </div></AppShell>;
}
